#pragma warning disable 0414, 0219, 0162, 0429, 0649
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// Blox Name: _8de6766ba2944c26bf290ec016285c7c
// Blox Ident: _8de6766ba2944c26bf290ec016285c7c
namespace BloxGenerated
{
    
    [BloxEngine.ExcludeFromBlox()]
    [UnityEngine.AddComponentMenu("")]
    public class _8de6766ba2944c26bf290ec016285c7c : UnityEngine.MonoBehaviour
    {
        public BloxEngine.BloxContainer bloxContainer;
        // Init
        public void Awake()
        {
            this.bloxContainer = this.GetComponent <BloxEngine.BloxContainer>();
        }
        // Event name: Start
        public void Start()
        {
            _Start_2c60();
            _Start_6fc4();
            _Start_a744();
        }
        // Event name: Start
        private void _Start_2c60()
        {
            if (false)
            {
            }
            UnityEngine.Debug.Log("300");
            if (false)
            {
            }
            UnityEngine.Debug.Log("300");
        }
        // Event name: Start
        private void _Start_6fc4()
        {
        }
        // Event name: Start
        private void _Start_a744()
        {
        }
        // Event name: FixedUpdate
        public void FixedUpdate()
        {
        }
        // Event name: Custom
        public void Custom(BloxEngine.BloxEventArg[] args)
        {
            _Custom_d404(args);
            _Custom_ff82(args);
        }
        // Event name: Custom
        private void _Custom_d404(BloxEngine.BloxEventArg[] args)
        {
        }
        // Event name: Custom
        private void _Custom_ff82(BloxEngine.BloxEventArg[] args)
        {
        }
    }
}
